language: haskell
notifications:
  email: false
install: /bin/true
script: travis_retry ./ci-test

language: haskell
notifications:
  email: false
before_install:
  - cabal install alex happy cpphs
  - cp ~/.cabal/bin/cpphs ./
  - cp ~/.cabal/bin/alex ./
  - cp ~/.cabal/bin/happy ./
install:
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests
script:
  - cabal configure --enable-tests
  - cabal build
  - ./dist/build/test/test